# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

# Writings
Writing.create(:article_title => "The Silencing of Domestic Violence Victims on Twitter", :description => "In this article I discuss waysin which communities can keep hashtags safe for survivors and how the user controls available are not enough.", :publication => "Model View Culture", :article_url => "https://modelviewculture.com/pieces/you-think-youre-helping-the-silencing-of-domestic-violence-victims-on-twitter")
Writing.create(:article_title => "Programmer Legitimacy: Earned, Bought, or Borrowed?", :description => "In this article I explore the current routes to becoming a programmer, and how those routes favor people with privilege", :publication => "Model View Culture", :article_url => "https://modelviewculture.com/pieces/programmer-legitimacy-earned-bought-or-borrowed")
Writing.create(:article_title => "TODO Group and the Open Source Code of Conduct", :description => "I discuss what makes a good code of conduct, and how the one proposed by TODO group fails marginalized people", :publication => "Model View Culture", :article_url => "https://modelviewculture.com/news/todo-group-and-open-source-codes-of-conduct")
# Writing.create(:article_title => "", :description => "", :publication => "", :article_url => "")

# Speakings
Speaking.create(:talk_name => "Programmer Legitimacy", :conference => "Lesbians Who Tech Berlin Summit", :conference_url => "", :slides_url => "", :video_url => "")
Speaking.create(:talk_name => "Going Your Own Way: When To Make A Gem", :conference => "RubyConf 2016", :conference_url => "", :slides_url => "", :video_url => "")
Speaking.create(:talk_name => "Data Visualization with Chartkick", :conference => "B'more On Rails Meet Up", :conference_url => "", :slides_url => "", :video_url => "")

#Codings
# Codes.create(:project_name => "", :description => "", :cool_point1 => "", :cool_point2 => "", :url => "", :github_url => "")
Codes.create(:project_name => "Businesses Against HB2", :description => "A website created after the NCGA and Pat McCrory signed HB2, which gutted rights for trans people and people who are lesbian, gay, bisexual, or otherwise not straight. It listed over 400 businesses that were opposed and had a list-building component. Design by Meena Yi and Kayla Bentley, content by Tessa Simonds. Pair-coded with Falon Shackelford.", :cool_point1 => "Made using PureCSS framework and using Javascript to pull from a Google Spreadsheet", :cool_point2 => "Rapid response project with a short time frame,", :url => "https://web.archive.org/web/20160428164453/https://businessesagainsthb2.com/", :github_url => "")
Codes.create(:project_name => "Your Republican Uncle", :description => "A website that saw many re-themeing events, designed to work on mobile and desktop to give talking points to Democrats during the holidays. Worked in conjunction with designer Meena Yi and content strategist Cate Domino", :cool_point1 => "The holiday theme had blinking lights with css animations and svg", :cool_point2 => "This was my first full static website created for a professional setting", :url => "https://web.archive.org/web/20151211210524/http://www.yourrepublicanuncle.com/", :github_url => "http://codepen.io/jdax/pen/pyMdYy")
Codes.create(:project_name => "GOPFather", :description => "A landing page to highlight a youtube video and promote list building during the primary, design by Meena Yi and content by Cate Domino, video by Eddie Geller and Rachel Velasquez ", :cool_point1 => "I made this at 11pm on a Saturday and had it built, tested, and deployed in 3 hours.", :cool_point2 => "Made with PureCSS and custom Sass mixins", :url => "", :github_url => "")
Codes.create(:project_name => "Has Chuck Grassley Done His Job", :description => "Created around when the 100 day mark had passed after President Obama nominated Garland for the Supreme Court. A counter that shows how long it's been since Obama made the nomination, built with Javascript. Designed by Meena Yi and Kayla Bently, content by Tessa Simonds and Cate Domino.", :cool_point1 => "Uses PureCSS and CSS transitions to change the background image.", :cool_point2 => "Uses npm scripts and Grunt to uglify, minify, and convert Sass to CSS.", :url => "http://haschuckgrassleydonehisjob.com/", :github_url => "")
Codes.create(:project_name => "Taxes By Trump", :description => "A base-engagement website built using npm scripts, Grunt, JQuery, Sass, and PureCSS, designed by Meena Yi, content by Cate Domino", :cool_point1 => "The submit button and social buttons use css transitions to change colors!", :cool_point2 => "This was rapid response and made, tested, and deployed in a day.", :url => "https://web.archive.org/web/20160602130723/https://taxesbytrump.com/", :github_url => "")
Codes.create(:project_name => "Status Alert System for CiviCRM", :description => "Using Angluar and PHP, created a status alert dashboard for CiviCRM, allowing a user to see any alerts, ranked by severity, and what actions need to be taken. Alerts could be hushed ('don't show me this again') or snoozed ('remind me on X day').", :cool_point1 => "First time using Angular", :cool_point2 => "First time writing professional object-oriented PHP API.", :url => "", :github_url => "https://github.com/civicrm/civicrm-core/pull/6957")
